spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:mem:elibdb;DB_CLOSE_DELAY=-1;MODE=MYSQL

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate:
      SQL: debug
      type: trace

---

spring:
  jackson:
    default-property-inclusion: non_null
  profiles: test
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
